name: python_on_gpus_rapids
channels:
  - conda-forge
  - rapidsai
dependencies:
  - cuda-version=13.0
  - jupyterlab
  - numpy
  - pandas
  - python=3.13
  - rapids=25.10

prefix: "/home/gjb/mambaforge/envs/python_on_gpus_rapids"
