name: python_on_gpus_numba
channels:
  - conda-forge
dependencies:
  - ca-certificates
  - certifi
  - cuda-nvcc
  - cuda-nvrtc
  - jupyterlab
  - matplotlib
  - numba
  - numba-cuda
  - numpy
  - openssl

prefix: "/home/gjb/mambaforge/envs/python_on_gpus_numba"
